### PR TITLE
Include imageio library in topical software

### PR DESCRIPTION
**Pull request by almarklein**

### CODE REVIEW

**Comment by almarklein** [comment]
cc @kuchi

**Comment by kuchi** [comment]
The link may be missing the 2nd ` character at the end.

**Comment by almarklein** [comment]
Ah, thanks. Hooray for the weird syntax for links in rst :(

**Comment by rgommers** [comment]
Looks good to me, merged.

**Comment by rgommers** [comment]
The laptop I'm traveling with isn't set up properly to upload to the host server, so this change isn't immediately reflected on the site.

**Comment by almarklein** [comment]
That's ok, as long as it gets there eventually :) thanks!

**Pull request merged**
