### PR TITLE
Update topical-software.rst

### PR DESCRIPTION
**Pull request by hvparks**
add metrolopy to science: basic tools

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @hvparks. I'm happy to add MetroloPy, however I'm thinking we should make a small subsection on units and also add other popular packages. Probably this is the list of most relevant ones: `pint`, `unyt`, `astropy.units`, `python-quantities` and `quantiphy`. What do you think?

**Comment by hvparks** [comment]
> I'm thinking we should make a small subsection on units and also add other popular packages

That would be great.  You might consider making the section also cover packages that do uncertainty propagation, e.g. `uncertainties`, `gtc`, and `scinum`.  Its not exactly the same thing, but if you are dealing with a value that has a unit it is likely to also have an uncertainty.

**Comment by hvparks** [comment]
> section also cover packages that do uncertainty propagation

Though I guess you do already have a section on automatic differentiation

**Comment by rgommers** [comment]
Before I forget this completely I'll push the green button and then look at the restructure I proposed. Thanks @hvparks

**Comment by rgommers** [comment]
>  and then look at the restructure I proposed.

Actually, I'll leave that for now, in favor of a more structural solution (see gh-99).

**Pull request merged**
