### PR TITLE
DOC: Update links for various libraries mentioned in documentation

### PR DESCRIPTION
**Pull request by gfyoung**
#150 was merged in too early, as there was a mistake in the package naming for `astropy` as pointed out by @anntzer.  In addition, I also stumbled upon the fact that the original link for the `.npy` format is outdated because it redirects you to the `numpy` repository.

### CODE REVIEW

**Comment by anntzer** [comment]
Now that we're there: the "topical software" page (http://scipy.org/topical-software.html) also has a link to pyfits that should be updated; the link just below to APLpy is also broken (now at https://aplpy.github.io/).

**Comment by gfyoung** [comment]
@anntzer : Done.  If there are any others, let me know!

**Comment by anntzer** [comment]
The "wrapping MATLAB" section should probably mention in first place the "official" bridges (http://www.mathworks.com/help/matlab/matlab-engine-for-python.html and http://www.mathworks.com/help/matlab/getting-started_buik_wp-3.html).  From personal experience they work reasonably well (I guess I should publicize my tiny wrapper around it).
In fact I'd probably drop pymat and mlabwrap from the list, the first one claims to support Python 2.2.3/Numeric 23(!) and the second one hasn't been updated since 2011.  The most recent open-source bridge seems to be https://github.com/arokem/python-matlab-bridge although I haven't tested it.

**Comment by gfyoung** [comment]
I agree with all of your suggestions except for the second MATLAB link because that's for bridging in other direction.

**Comment by anntzer** [comment]
Well, the list included pythoncall which is also going in the other direction.  Also edited the previous post for more suggestions.

**Comment by gfyoung** [comment]
Ah, good point regarding `pythoncall`.  Then I'll add the other link you suggested.

**Comment by gfyoung** [comment]
Regarding `Anaconda` and `Python(x,y)`, there seemed to be a nice home for them under the "Working environments" section (that's where `Canopy` is located as well), so I just moved them there.

**Comment by anntzer** [comment]
paramnormal is also weirdly emphasized (probably a markup issue).

**Comment by gfyoung** [comment]
The paramnormal emphasis was due to a stray whitespace character preceding the word, which causes it to be formatted differently.

**Comment by gfyoung** [comment]
Seems that this PR has outgrown its original purpose, but oh well.  Are there any other bad links that should be fixed in this PR?  If not, this should be good to merge.

**Comment by anntzer** [comment]
More kitchen sink (randomly clicking on dubious links):
Weird markup in the gnuplot.py entry.
Link to graceplot is broken.
I guess Veusz doesn't use numarray anymore (and anyways the link to numarray is broken).
Mayavi V1 dates back to 2005 and should probably be removed.
pyqtgraph is great but probably isn't worth being mentioned three times (with different descriptions).
I guess that pyhdf (HDF4) which hasn't been updated since 2008 should be replaced by the python-hdf4 fork (https://github.com/fhs/python-hdf4) (which I have no experience with either).
If PyOpenCL is mentioned I guess PyCUDA also deserves a spot.
The "tutorial" entry in Astronomy points to a pdf dating back to 2007, probably out of date.
> pyem is a tool for Gaussian Mixture Models. It implements EM algorithm for Gaussian mixtures (including full matrix covariances), BIC criterion for clustering. Since october 2006, it is included in scipy toolbox.

Looks like it went into sklearn in fact.
> Python/Tk Viewer for the NCBI Taxonomy Database A viewer for the NCBI taxonomy database, written in Python/Tk, was developed in 1998.

Well, the link is broken anyways.
Link to MNE-Python should be updated to http://www.martinos.org/mne/stable/index.html
Pymacs, Simpy, Pyarie, GarlicSim, pyTrix, BALL - Biochemical Algorithms Library, swiginac, nzmath, decint have broken links.
Pandas probably deserves a better spot.
A number of libraries are mentioned as "See entry in Misc" and probably should be sorted out.
mwavepy is now scikit-rf (new link).
Pythonica link should be updated and the project says it's defunt anyways.
larry is nice but you should probably mention xarray instead.
gmpy seems dead, gmpy2 more active?
pygsl seems dead, cygsl less dead.
paida seems dead, pyamg moved to github.
Links to PyIMSLStudio, Instand are dead.
I guess Weave is essentially deprecated although I don't know if there's any replacement.
rpy is now rpy2
According to their own webpage,
> pyidlrpc has been made part of the mirpyidl project and is now considered depreciated.

biggles moved to github
Both links to OpenCV, link to pyepix, dot2tex are broken.
pychart: "The latest version is pychart-1.39 (1/1/2006)."
Py-OpenDX says it's been last updated in 2001, links to Py2DX, Pivy, panda3d, pygeo, spacefuncs, openopt, pulp are dead (there's also a bunch of other projects previously hosted under openopt.org which probably moved too).
IVuPy, APLEpy, CVExp also seem pretty old.
pylinpro is... a single source posted as a blog entry?
"Pyreport is unmaintained"
Coopr is now Pyomo.
Link to CVXOPT is dead (although I think the project is still alive).
Link to EMMA should be emma-project.org

Link to pypar is dead; parallel programming should probably also mention joblib.
A discussion on Python and MPI: very useful discussion on this topic, carried at the CSC Climate Wiki.: DEAD
pypvm: Version 0.94 adds support for python 2.3.

Actually you may just want to grep for all links pointing to google code and update them...

**Comment by anntzer** [comment]
And that's not mentioning all the better tools that came out since then...

A couple of places directly mention stuff in scipy, that seems a bit strange perhaps.

**Comment by anntzer** [comment]
On the FAQ side:
What are SciPy’s licensing terms?
SciPy’s license is free for both commercial and non-commercial use, the terms of the BSD license. (TODO: Link) <--
Well there's a couple more TODOs.

The entry for "Why doesn’t A[[0, 1, 1, 2]] += 1 do what I think it should?" should probably mention `ufunc.at` (e.g. `np.add.at`).

**Comment by anntzer** [comment]
http://www.numpy.org/old_array_packages.html

May not even belong here but well, the link's accessible from scipy.org

> Numeric users should find the transition relatively easy (although not without some effort). There is a module (numpy.oldnumeric.alter_code1) that can make most of the necessary changes to your Python code that used Numeric to work with NumPy’s Numeric compatibility module.
Users of numarray can also transition their code using a similar module (numpy.numarray.alter_code1) and the numpy.numarray compatibility layer.

I guess no one cares anymore but the modules don't exist anymore.  Also mentioned below.

> Sponsors of numarray have indicated they will be moving to NumPy as soon as is feasible for them so that eventually numarray will be phased out (probably sometime in 2007).

ha, ha, ha.

**Comment by anntzer** [comment]
I also wonder whether all mentions of IPython should be replaced by jupyter.

**Comment by Eric89GXL** [comment]
Sure, just mention early on that it was formerly known as IPython.

**Comment by pv** [comment]
Thanks for rummaging in the attic :)

I think there's some use for a curated page, given that pypi doesn't have anything better than this: https://pypi.python.org/pypi?:action=browse&show=all&c=40 --- not sure if this wiki-style page is the most efficient approach (cf gh-99). Don't have the bandwidth to try to do something about this currently, though.

**Comment by takluyver** [comment]
Ipython/Jupyter is not a straight rename - the parts for executing and
introspecting Python code are still IPython. Jupyter is the language
agnostic parts. So don't go too crazy with find & replace! ;-)

**Comment by gfyoung** [comment]
I think it would be better to rename it in the doc as `IPython/Jupyter` instead of just `IPython` given that it isn't a direct rename as you said @takluyver .

**Comment by gfyoung** [comment]
Decided to just add the `Jupyter Notebook` to the environments section so that people are aware of it.  In addition to the second kitchen sink, also cleaned up the FAQ license and `at` functionalities.  If there are no more sinks to throw, this should be good to go then.

**Comment by pv** [comment]
Thanks, merged.

Note that you can run `cd www; make linkcheck` and Sphinx will check the links for you.

**Comment by gfyoung** [comment]
@pv: That's a good point.  I'll do that as a follow-up.

**Comment by pv** [comment]
Looks like quite a lot of them are broken . . . :/

**Comment by gfyoung** [comment]
Should be another fun PR. :smile:

**Pull request merged**
