### PR TITLE
DOC: Add NetworkX to ecosystem page.

### PR DESCRIPTION
**Pull request by rossbar**
Adds NetworkX to the "Data and computation" category of the about page which describes the scipy ecosystem.

### CODE REVIEW

**Comment by jarrodmillman** [comment]
@rgommers Does this seem reasonable?

**Comment by jarrodmillman** [comment]
@pv @charris @stefanv @tylerjereddy Does this seem reasonable?  NX is widely used and has a long history as being a fundamental part of ecosystem.  It was one of the few packages specifically mentioned in the "Python: An Ecosystem for Scientific Computing" by Fernando et al.  Jake included it in his widely used schematic view of the Python scientific software ecosystem.  We also included it the recent "Array Programming with NumPy" diagram of the scientific Python ecosystem.

**Comment by charris** [comment]
+1 From me.

**Comment by rgommers** [comment]
Oh sorry, I skimmed the title earlier and assumed it was about numpy.org. This is a no-brainer indeed, in it goes. Thanks @rossbar and @jarrodmillman

**Pull request merged**
