### PR TITLE
Add Code of Conduct to navigation sidebar

### PR DESCRIPTION
**Pull request by stefanv**
I asked a friend for feedback on our CoC, and she noted that it was not very easy to find.  I added it to the sidebar, and will make another PR to add it to the README as well.

### CODE REVIEW

**Comment by rgommers** [comment]
+1 good idea

**Comment by rgommers** [comment]
It's in the wrong place though, it should be in the sidebar of https://scipy.org/scipylib/index.html. That's the front page for SciPy the library; the CoC is not for the ecosystem.

**Comment by stefanv** [comment]
So... hrm. SciPy.org seems like the landing place for all SciPy related 
activities? E.g., there are links at the top (the big icons!) to file bug 
reports to the library. The CoC would be most discoverable here, but if we 
only mention it elsewhere we should probably also remove items related to 
the library from this page, other than perhaps a pointer to the library?

**Comment by pv** [comment]
The bug report links lead to bug trackers of all projects, not only scipy.

**Comment by pv** [comment]
and ditto for all other links, iirc thetes nothing project såecific on the front page

**Comment by rgommers** [comment]
@stefanv yes this is partly the problem with scipy.org - it's for the ecosystem, but it's too limited for that, while the library pages are hidden. that's one of the things I wanted to discuss next week.

**Comment by rgommers** [comment]
We could address that by a new page "Code of Conducts" which links to all the ones for individual projects. That keeps it very visible.

**Comment by rgommers** [comment]
- SciPy CoC: http://scipy.github.io/devdocs/dev/conduct/code_of_conduct.html
- Pandas CoC: https://github.com/pandas-dev/pandas-governance/blob/master/code-of-conduct.md
- NumPy CoC: doesn't exist (yet)
- Matplotlib CoC: doesn't exist (yet)
- Sympy CoC: https://github.com/sympy/sympy/blob/master/CODE_OF_CONDUCT.md
- Jupyter/IPython CoC: https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md

**Comment by stefanv** [comment]
I updated the PR with this suggestion (CoC page added that lists CoC's for all 6 projects shown on the website, and an entry for the SciPy library).

**Comment by rgommers** [comment]
I'll wait for a day or two with merging, but this looks good to me.

**Comment by rgommers** [comment]
No objections, so in it goes. Thanks Stefan!

**Comment by rgommers** [comment]
@nellev FYI https://scipy.org/codes-of-conduct.html - would be good not to forget to update this in case Matplotlib gains itself a CoC.

**Comment by NelleV** [comment]
Yep, I'll keep this in mind!

**Comment by tacaswell** [comment]
For several years we have had "Matplotlib is a welcoming, inclusive project, and we try to follow the Python Software Foundation Code of Conduct in everything we do."  on the main matplotlib.org page.

**Comment by rgommers** [comment]
@tacaswell do you want to put that back up your website for the time being? Then we can link to / mention that.

**Comment by tacaswell** [comment]
It is still there, but we have not dedicated CoC page.

**Pull request merged**
