### PR TITLE
Update team members

### PR DESCRIPTION
**Pull request by tupui**
FYI, @stefanv you are still not in the GH list for the web team and I think you should be. I manually update the list to have you there.

### CODE REVIEW

**Comment by stefanv** [comment]
Won't this just get overwritten next time you generate the gallery?

**Comment by stefanv** [comment]
For now, I've added myself to the web team to simplify your life. Do you need any other people added to teams?

**Comment by tupui** [comment]
haha thanks. I think otherwise it's good. At leat with what I know :)

**Comment by tupui** [comment]
Pushing this now.

**Pull request merged**
