### PR TITLE
MAINT: fix "make upload"

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
- new.scipy.org not relevant anymore
- ``make upload`` now runs without any errors. that never happened before. looks like we don't need the ``fixperm-scipy_org`` script anymore, permissions look fine as is.

**Comment by pv** [comment]
Why the --chown option would work is unclear if you are not uploading as 
root.
.
It's unclear if the upload will work for other users than you, without 
fixing the permissions to group-writable.

**Comment by pv** [comment]
But let's try to push the move to S3 or github pages ASAP, so that all 
this goes away.

**Comment by rgommers** [comment]
> Why the --chown option would work is unclear if you are not uploading as root.

Not 100% sure but it does. Didrik changed something for ```www-data`` with ``setuid``/``setgid`` to make this work.

> But let's try to push the move to S3 or github pages ASAP, so that all this goes away.

That'd be good indeed. Enthought people are looking into it.

This is still a useful PR to merge I think, fixes several issues aside from the ``chown``.

**Pull request merged**
