### PR TITLE
DOC: remove IRC section

### PR DESCRIPTION
**Pull request by tupui**
xref https://github.com/scipy/scipy/issues/14239#issuecomment-904653674

This removes the IRC section from the mailing list page.

### CODE REVIEW

**Comment by tupui** [comment]
Also seeing that the search links are not working. I could remove/replace them.

http://scipy-user.10969.n7.nabble.com
http://numpy-discussion.10968.n7.nabble.com

**Comment by mdhaber** [comment]
LGTM. Eliminating/fixing broken links also sounds good. Let me know if you'd like to do that here.

**Comment by tupui** [comment]
I removed the broken links.

**Review by rgommers — APPROVED** [review]
LGTM, thanks @tupui

**Pull request merged**
