### PR TITLE
Change text on posting jobs on mailing lists

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by andyfaff** [comment]
There's a small suggestion I'd like to make

**Comment by rgommers** [comment]
@andyfaff please do:)

**Comment by andyfaff** [comment]
When I first sat down this morning it didn't seem to scan right. That was before I had a cup of tea though, it looks ok now.

**Comment by rgommers** [comment]
Tea or coffee makes everything look better:)

**Pull request merged**
