### PR TITLE
LICENSE

### PR DESCRIPTION
**Pull request by gaushikmr**

### CODE REVIEW

**Comment by ilayn** [comment]
Hi @gaushikmr . Do you mind elaborating what you want to do? SciPy is BSD-licensed anyways and License file is already in the actual codebase. This is the repo for the website. 

https://github.com/scipy/scipy/blob/master/LICENSE.txt

**Comment by gaushikmr** [comment]
@ilayn ok I will close this.

**Comment by rgommers** [comment]
@gaushikmr actually does have a point, every repo should have a `LICENSE` file. That said, it should indeed be the same license and the same copyright attribution as the main repo.

**Comment by ilayn** [comment]
You can add BSD-3 from the available options in the GitHub settings for this repo.

**Comment by gaushikmr** [comment]
@ilayn OK I will add BSD-3

**Pull request closed without merging**
