### PR TITLE
DOC: add description of what the `scipy` IRC channel is for.

### PR DESCRIPTION
**Pull request by rgommers**
Triggered by mailing list discussion starting on 22 Feb 2018.

### CODE REVIEW

**Comment by pv** [comment]
Maybe we could also add the sentence:
```
If you are new to IRC, you may be interested in reading `How to get 
useful help on IRC <debian-irchelp>`__.

.. _debian-irchelp: https://wiki.debian.org/GettingHelpOnIrc
```

**Comment by rgommers** [comment]
Thanks @pv, done

**Comment by pv** [comment]
Sorry, I made a mistake in RST link formatting --- it should be 
```<debian-irchelp_>``` not ```<debian-irchelp>```.

Otherwise lgtm.

**Comment by rgommers** [comment]
That's what I get for updating a PR without checking:( Fixed now.

**Pull request merged**
