### PR TITLE
Update mailing lists page.  Remove links to Gmane, add Stackoverflow.

### PR DESCRIPTION
**Pull request by rgommers**
Note that there is no scipy-dev Nabble forum, so we lost easy
searchability for scipy-dev.  We may look into creating such a forum
soon.

### CODE REVIEW

**Comment by pv** [comment]
I would hold it until it becomes clear that Nabble admins update the mailing list addresses. I'm not sure if this will happen: the numpy/scipy forums were created by someone (username "Timmie" there), and I'm not sure if the site admins will touch requests to change someone's forum settings. 

The mailing lists probably will become searchable via Google et al. anyway, although it may take some time before they get crawled --- the scipy.org archives can be searched:
https://www.google.fi/search?q=site:http://mail.scipy.org/pipermail/scipy-dev/+running+tests

**Comment by rgommers** [comment]
They're both updated, here are messages from today:

http://numpy-discussion.10968.n7.nabble.com/Fwd-SciPy2017-Sprints-FinAid-for-sprint-leaders-core-devs-td44132.html

http://scipy-user.10969.n7.nabble.com/SciPy-User-Announcement-scikit-image-0-13-0-tt20871.html

**Comment by pv** [comment]
I'm not sure if that's the case. Nabble is probably subscribed to the 
list as usual, and the subscriber list was transferred by us.

**Comment by pv** [comment]
Anyway, if you think it works, please go ahead.

**Comment by rgommers** [comment]
Either way it's much better than a dead link. I'll merge and set a reminder for myself to check in a week or two that the archive is complete. If not, we may just want to create new forums on Nabble, or search for an alternative.

**Comment by rgommers** [comment]
Just checked: both Nabble forums are still updating

http://scipy-user.10969.n7.nabble.com/
http://numpy-discussion.10968.n7.nabble.com/

**Pull request merged**
