### PR TITLE
Announce SciPy 1.6.3

### PR DESCRIPTION
**Pull request by tylerjereddy**
Announce SciPy 1.6.3

### CODE REVIEW

**Review by tupui — APPROVED** [review]

**Comment by tupui** [comment]
Thanks Tyler. Looking at other similar PRs LGTM so merging.

**Comment by rgommers** [comment]
Thanks for another useful release shipped Tyler!

Website updated now. @tupui it's better not to merge unless you can also deploy to the server that hosts scipy.org and docs.scipy.org. When we redo the website we should migrate away from that server to something saner (GitHub Pages or Netlify), but for now it's only a few people who have ssh access.

**Comment by tupui** [comment]
> Website updated now. @tupui it's better not to merge unless you can also deploy to the server that hosts scipy.org and docs.scipy.org. When we redo the website we should migrate away from that server to something saner (GitHub Pages or Netlify), but for now it's only a few people who have ssh access.

Oh sorry I didn't know 🙇‍♂️  
Not sure how/when the new website will happen. Are we going (have we already) to make some open calls for that?

**Comment by rgommers** [comment]
No worries at all. It's a bit outdated unfortunately.

> Not sure how/when the new website will happen. Are we going (have we already) to make some open calls for that?

I'd like to wait till we know about a possible CZI cycle 4 grant, that would give us someone with bandwidth to coordinate a complete redesign at once. If that's not successful, we can tackle it in a fashion that's more incremental.

**Pull request merged**
