### PR TITLE
Added: vibrationtesting, vibration_toolbox, mousai

### PR DESCRIPTION
**Pull request by josephcslater**
Vibration_Toolbox (re-envisioning of 27 year-old Matlab toolbox by the same name).

VibrationTesting: signal processing, model updating, correction, solution, identificaiton

array_to_latex: numpy arrays to formatted latex

mousai: harmonic balance solver for `large` ODEs.

### CODE REVIEW

**Comment by josephcslater** [comment]
> On Mar 26, 2018, at 12:22 AM, Ralf Gommers <notifications@github.com> wrote:
> 
> Thanks @josephcslater.
> 
> I would say that for array_to_latex, it would be better to add to the SciPy Cookbook (http://scipy-cookbook.readthedocs.io, repo at https://github.com/scipy/scipy-cookbook), it's basically a single function so doesn't clear the bar for inclusion here. The others look good!

You are best to judge. I wasn't even aware of the cookbook. 
Best Regards- Joe

**Comment by josephcslater** [comment]
Should be good now. I'll put array_to_latex in the cookbook later.

**Comment by josephcslater** [comment]
array_to_latex might be best tucked into one of the existing notebooks. I'll have to edit up something nice. In the mean time, I cleaned one up just a bit. scipy->SciPy in the text, and so on.

**Comment by rgommers** [comment]
Merged, thanks @josephcslater

**Comment by josephcslater** [comment]
Ha! That gratitude is to you. I don't know how you do it all.

**Pull request merged**
