### PR TITLE
Update install.rst

### PR DESCRIPTION
**Pull request by alanyee**
-Update install instructions for scipy
-Made explicit HTTPs calls
-Minor url cleanups

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @alanyee. It looks like you forgot to commit your changes to the install instructions.

**Comment by alanyee** [comment]
@rgommers what do you mean?

**Comment by rgommers** [comment]
> @rgommers what do you mean?

The first commit had no changes that looked like *Update install instructions for scipy*. Guess you meant with that the changes to Homebrew instructions that you pushed in your second commit.

**Comment by rgommers** [comment]
Merged, thanks @alanyee

**Pull request merged**
