### PR TITLE
Change installation instructions to promote pip + remove references to "scipy stack"

### PR DESCRIPTION
**Pull request by pv**
Update the installation instructions:

- Remove references to the "scipy stack" (following #218)
- Promote using pip also on Windows

We may want to wait until scipy 1.0 is out in order to have the windows wheels...

### CODE REVIEW

**Comment by xoviat** [comment]
Also, there is a pip packaged called `scipy-stack`. So after 1.0 is released, you can download Python from Python.org and then type `pip install scipy-stack` and everything will work (Jupyter, IPython, numpy, scipy, etc...).

**Comment by pv** [comment]
ready?

**Comment by xoviat** [comment]
Yes but it has no code, only dependencies. You could ask for maintainer access.

**Comment by xoviat** [comment]
@David-OConnor

**Comment by pv** [comment]
Well, given that we decided the whole concept is not necessary any more, I think we won't re-add it in this PR.

**Comment by xoviat** [comment]
BTW, how do you auto cancel the old PR builds? I could not find that option. 

But yes, looks okay.

**Comment by David-OConnor** [comment]
Re the scipy-stack convenience package: There's not much to maintain! It should install properly on Windows, now that Scipy 1.0.0 is out.

**Comment by pv** [comment]
Ok, I'll just merge it. If there's something to change we can mop it up later.

**Pull request merged**
