### PR TITLE
Update Nature Methods paper citation information

### PR DESCRIPTION
**Pull request by mdhaber**

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
Makes sense--we probably forgot to update the plain-text version when we added the volume & page info to the BibTeX  entry.

**Comment by tylerjereddy** [comment]
Thanks @mdhaber

**Comment by andyfaff** [comment]
Citations are going gangbusters on Google Scholar. Fortunately or unfortunately it eclipses all my day job science.

**Comment by tylerjereddy** [comment]
Same here, and really great to see! I hope it paves the path for some of us to get bits of funding for it here and there.

**Pull request merged**
